/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.5.1/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply Spotless for formatting enforcement (uses ktlint under the hood).
    alias(libs.plugins.spotless)

    // Apply Detekt for static analysis on Kotlin source.
    alias(libs.plugins.detekt)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest(libs.versions.kotlin.get())
        }

        // Create a new test suite
        val functionalTest by registering(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest(libs.versions.kotlin.get())

            dependencies {
                // functionalTest test suite depends on the production code in tests
                implementation(project())
            }

            targets {
                all {
                    // This test suite should run after the built-in test suite has run its tests
                    testTask.configure { shouldRunAfter(test) }
                }
            }
        }
    }
}

gradlePlugin {
    // Define the plugin
    val greeting by plugins.creating {
        id = "com.billgonemad.dependencypulse.greeting"
        implementationClass = "com.billgonemad.dependencypulse.DependencyPulsePlugin"
    }
}

gradlePlugin.testSourceSets.add(sourceSets["functionalTest"])

tasks.named<Task>("check") {
    // Include functionalTest as part of the check lifecycle
    dependsOn(testing.suites.named("functionalTest"))
}

// --- Kotlin compiler guardrail ---
// Treat all Kotlin compiler warnings as errors on every KotlinCompile task
// (main + test + functionalTest source sets). Catches deprecation usages,
// unsafe casts, redundant null checks, etc. before they land in main.
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions {
        allWarningsAsErrors.set(true)
    }
}

// --- Spotless formatting guardrail ---
// Two extensions: kotlin{} for source .kt files, kotlinGradle{} for *.gradle.kts.
// Using both is required — the kotlin extension does NOT pick up build scripts.
spotless {
    kotlin {
        // Covers main, test, and functionalTest source sets — all live under src/<sourceSet>/kotlin.
        target("src/**/*.kt")
        targetExclude("**/build/**")
        ktlint(libs.versions.ktlint.get())
    }
    kotlinGradle {
        target("*.gradle.kts", "**/*.gradle.kts")
        targetExclude("**/build/**")
        ktlint(libs.versions.ktlint.get())
    }
}

// --- Detekt static-analysis guardrail ---
// Source coverage: all three source sets (main + test + functionalTest).
// The default detekt task covers main + test automatically; functionalTest
// requires explicit inclusion via detekt.source.
//
// Fail behavior: Detekt 1.23.x's default (ignoreFailures = false, plus per-rule
// severity in detekt.yml) already gives us "error-severity findings fail the build,
// warning-severity findings report but do not fail." No explicit failOnSeverity
// property is needed for the default ruleset. If you change a rule's severity in
// detekt.yml, that severity governs whether it fails the build.
detekt {
    config.setFrom(rootProject.file("detekt.yml"))
    buildUponDefaultConfig = true
    source.setFrom(
        files(
            "src/main/kotlin",
            "src/test/kotlin",
            "src/functionalTest/kotlin",
        ),
    )
    // ignoreFailures defaults to false — leave as-is. Build fails on error-severity rule hits.
}

// Configure JVM target for Detekt tasks to match Kotlin compilation.
tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
    jvmTarget = "21"
}

// The Detekt plugin attaches the `detekt` task to `check` automatically.
